/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppDarkModeToggle: (typeof import('./../src/components/Application/src/AppDarkModeToggle.vue'))['default'];
    AppLocalePicker: (typeof import('./../src/components/Application/src/AppLocalePicker.vue'))['default'];
    AppLogo: (typeof import('./../src/components/Application/src/AppLogo.vue'))['default'];
    AppProvider: (typeof import('./../src/components/Application/src/AppProvider.vue'))['default'];
    BasicArrow: (typeof import('./../src/components/Basic/src/BasicArrow.vue'))['default'];
    BasicDrawer: (typeof import('./../src/components/Drawer/src/BasicDrawer.vue'))['default'];
    BasicHelp: (typeof import('./../src/components/Basic/src/BasicHelp.vue'))['default'];
    BasicMenu: (typeof import('./../src/components/Menu/src/BasicMenu.vue'))['default'];
    BasicTitle: (typeof import('./../src/components/Basic/src/BasicTitle.vue'))['default'];
    CollapseContainer: (typeof import('./../src/components/Container/src/collapse/CollapseContainer.vue'))['default'];
    CollapseHeader: (typeof import('./../src/components/Container/src/collapse/CollapseHeader.vue'))['default'];
    CollapseTransition: (typeof import('./../src/components/Transition/src/CollapseTransition.vue'))['default'];
    Drawer: (typeof import('./../src/components/Drawer/index.vue'))['default'];
    Dropdown: (typeof import('./../src/components/Dropdown/src/Dropdown.vue'))['default'];
    Icon: (typeof import('./../src/components/Icon/Icon.vue'))['default'];
    IconPicker: (typeof import('./../src/components/Icon/src/IconPicker.vue'))['default'];
    Menu: (typeof import('./../src/components/SimpleMenu/src/components/Menu.vue'))['default'];
    MenuCollapseTransition: (typeof import('./../src/components/SimpleMenu/src/components/MenuCollapseTransition.vue'))['default'];
    MenuItem: (typeof import('./../src/components/SimpleMenu/src/components/MenuItem.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    Scrollbar: (typeof import('./../src/components/Scrollbar/src/Scrollbar.vue'))['default'];
    ScrollContainer: (typeof import('./../src/components/Container/src/ScrollContainer.vue'))['default'];
    SimpleMenu: (typeof import('./../src/components/SimpleMenu/src/SimpleMenu.vue'))['default'];
    SimpleMenuTag: (typeof import('./../src/components/SimpleMenu/src/SimpleMenuTag.vue'))['default'];
    SimpleSubMenu: (typeof import('./../src/components/SimpleMenu/src/SimpleSubMenu.vue'))['default'];
    SubMenuItem: (typeof import('./../src/components/SimpleMenu/src/components/SubMenuItem.vue'))['default'];
    SvgIcon: (typeof import('./../src/components/Icon/src/SvgIcon.vue'))['default'];
  }
}
