/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent'];
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter'];
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader'];
    AMenu: (typeof import('./../src/components/SimpleMenu/src/components/AMenu.vue'))['default'];
    AppProvider: (typeof import('./../src/components/Application/src/AppProvider.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
