/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ALayoutContent: (typeof import('ant-design-vue/es'))['LayoutContent'];
    ALayoutFooter: (typeof import('ant-design-vue/es'))['LayoutFooter'];
    ALayoutHeader: (typeof import('ant-design-vue/es'))['LayoutHeader'];
    AMenu: (typeof import('./../src/components/SimpleMenu/src/components/AMenu.vue'))['default'];
    AppProvider: (typeof import('./../src/components/Application/src/AppProvider.vue'))['default'];
    BasicMenu: (typeof import('./../src/components/Menu/src/BasicMenu.vue'))['default'];
    CollapseTransition: (typeof import('./../src/components/Transition/src/CollapseTransition.vue'))['default'];
    Icon: (typeof import('./../src/components/Icon/Icon.vue'))['default'];
    IconPicker: (typeof import('./../src/components/Icon/src/IconPicker.vue'))['default'];
    Menu: (typeof import('./../src/components/SimpleMenu/src/components/Menu.vue'))['default'];
    MenuCollapseTransition: (typeof import('./../src/components/SimpleMenu/src/components/MenuCollapseTransition.vue'))['default'];
    MenuItem: (typeof import('./../src/components/SimpleMenu/src/components/MenuItem.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
    SimpleMenu: (typeof import('./../src/components/SimpleMenu/src/SimpleMenu.vue'))['default'];
    SimpleMenuTag: (typeof import('./../src/components/SimpleMenu/src/SimpleMenuTag.vue'))['default'];
    SimpleSubMenu: (typeof import('./../src/components/SimpleMenu/src/SimpleSubMenu.vue'))['default'];
    SubMenuItem: (typeof import('./../src/components/SimpleMenu/src/components/SubMenuItem.vue'))['default'];
    SvgIcon: (typeof import('./../src/components/Icon/src/SvgIcon.vue'))['default'];
  }
}
